servingEngineSpec:
  runtimeClassName: ""
  modelSpec:
  - name: "llama1b"
    repository: "vllm/vllm-openai"
    tag: "latest"
    modelURL: "meta-llama/Llama-3.2-1B-Instruct"

    replicaCount: 1

    requestCPU: 6
    requestMemory: "16Gi"
    requestGPU: 1

    envFromSecret:
      name: "dotenv-secret"

# Tutorial here: https://docs.vllm.ai/projects/production-stack/en/latest/getting_started/prerequisite.html

# Extra steps for authenticating with hugging face 
# 1: Make .env file with the following content:
# HUGGING_FACE_HUB_TOKEN=your_token_here
# 2: Run the following command to create the secret:
# kubectl create secret generic dotenv-secret --from-env-file=.env
# 3: Run the following command to apply the configuration:
# helm install vllm vllm/vllm-stack -f tutorials/assets/values-01-minimal-example.yaml
